apiVersion: v1
kind: PersistentVolume
metadata:
  name: alicesrabbit-pv
  labels:
    type: local
    app: alicesrabbit
  namespace: alicesrabbit
spec:
  storageClassName: alicesrabbit-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alicesrabbit-pvc
  labels:
    app: alicesrabbit
  namespace: alicesrabbit
spec:
  storageClassName: alicesrabbit-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi